# Database schema - table structure
CREATE_QUERIES = {
    "version": """CREATE TABLE IF NOT EXISTS version (
        version_id varchar(10) PRIMARY KEY,
        version_comment varchar, 
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        consumer_categories varchar,
        connection_available_cables varchar,   
        other_parameters varchar
    )
    """,
    "equipment_data": """
   CREATE TABLE IF NOT EXISTS equipment_data(
       version_id       varchar(10)  NOT NULL,
       name             varchar(100) NOT NULL,
       s_max_kva        integer,
       max_i_a          integer,
       r_mohm_per_km    integer,
       x_mohm_per_km    integer,
       z_mohm_per_km    integer,
       cost_eur         integer,
       typ              varchar(50),
       CONSTRAINT equipment_data_pkey PRIMARY KEY (version_id, name),
       CONSTRAINT fk_equipment_data_version
           FOREIGN KEY (version_id)
               REFERENCES version (version_id)
               ON DELETE CASCADE
   )
    """,
    "classification_version": """
    CREATE TABLE IF NOT EXISTS classification_version (
        classification_id integer NOT NULL,
        classification_version_comment varchar, 
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        classification_region varchar,
        CONSTRAINT classification_pkey PRIMARY KEY (classification_id)
    )
    """,
    "postcode": """
    CREATE TABLE IF NOT EXISTS postcode (
        postcode_id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        plz integer UNIQUE NOT NULL,
        allocated_plz integer,
        note varchar,
        qkm double precision,
        population integer,
        geom geometry(MultiPolygon,3035),
        CONSTRAINT "plz-5stellig_pkey" PRIMARY KEY (postcode_id)
    )
    """,
    "postcode_result": """
    CREATE TABLE IF NOT EXISTS postcode_result (   
        version_id varchar(10) NOT NULL,
        postcode_result_plz integer NOT NULL,
        geom geometry(MultiPolygon,3035),
        house_distance double precision,
        avg_households_per_building double precision,
        settlement_type integer,
        
        CONSTRAINT "postcode_result_pkey" PRIMARY KEY (version_id, postcode_result_plz),
        CONSTRAINT fk_postcode_result_version_id
            FOREIGN KEY (version_id)
            REFERENCES version (version_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_postcode_result_plz
            FOREIGN KEY (postcode_result_plz)
            REFERENCES postcode (plz)
            ON DELETE CASCADE
    )
    """,
    "grid_result": """
    CREATE TABLE IF NOT EXISTS grid_result (
        grid_result_id SERIAL PRIMARY KEY,
        version_id varchar(10) NOT NULL,
        kcid integer NOT NULL,
        bcid integer NOT NULL,
        plz integer NOT NULL,
        transformer_rated_power bigint,
        transformer_equipment_name varchar(100),
        transformer_description varchar(100),
        model_status integer,

        CONSTRAINT fk_grid_result_version_id
            FOREIGN KEY (version_id)
            REFERENCES version (version_id)
            ON DELETE CASCADE
    )
    """,
    "buildings" : """CREATE TABLE IF NOT EXISTS buildings (
        osm_id bigint PRIMARY KEY,
        plz integer,
        type varchar,
        area double precision,
        households_per_building double precision,
        peak_load_in_kw double precision,
        floors integer,
        center geometry(Point,3035),
        geom geometry(Polygon,3035)
    )
    """,
    "transformers": """CREATE TABLE IF NOT EXISTS transformers (
        osm_id bigint PRIMARY KEY,
        plz integer,
        power double precision,
        geom geometry(Point,3035)
    )
    """,
    "ways": """CREATE TABLE IF NOT EXISTS ways (
        gid SERIAL PRIMARY KEY,
        osm_id bigint,
        plz integer,
        name varchar,
        fclass varchar,
        geom geometry(LineString,3035)
    )
    """,
    "ways_nodes": """CREATE TABLE IF NOT EXISTS ways_nodes (
        id bigint PRIMARY KEY,
        plz integer,
        geom geometry(Point,3035)
    )
    """,
    "buildings_result": """CREATE TABLE IF NOT EXISTS buildings_result (
        version_id varchar(10) NOT NULL,
        osm_id bigint NOT NULL,
        grid_result_id integer,
        plz integer,
        area double precision,
        type varchar,
        households_per_building double precision,
        peak_load_in_kw double precision,
        floors integer,
        vertice_id integer,
        connection_point geometry(Point,3035),
        center geometry(Point,3035),
        geom geometry(Polygon,3035),

        CONSTRAINT buildings_result_pkey PRIMARY KEY (version_id, osm_id, plz),
        CONSTRAINT fk_buildings_result_version_id
            FOREIGN KEY (version_id)
            REFERENCES version (version_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_buildings_result_grid_result_id
            FOREIGN KEY (grid_result_id)
            REFERENCES grid_result (grid_result_id)
            ON DELETE SET NULL
    )
    """,
    "grids": """CREATE TABLE IF NOT EXISTS grids (
        grid_id SERIAL PRIMARY KEY,
        version_id varchar(10) NOT NULL,
        plz integer,
        kcid integer,
        bcid integer,
        grid jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

        CONSTRAINT fk_grids_version_id
            FOREIGN KEY (version_id)
            REFERENCES version (version_id)
            ON DELETE CASCADE
    )
    """,
    "lines_result": """CREATE TABLE IF NOT EXISTS lines_result (
        version_id varchar(10) NOT NULL,
        grid_result_id integer,
        from_bus integer,
        to_bus integer,
        cable_equipment_name varchar(100),
        r_ohm_per_km double precision,
        x_ohm_per_km double precision,
        c_nf_per_km double precision,
        length_km double precision,
        max_i_ka double precision,
        parallel integer,
        geom geometry(LineString,3035),

        CONSTRAINT fk_lines_result_version_id
            FOREIGN KEY (version_id)
            REFERENCES version (version_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_lines_result_grid_result_id
            FOREIGN KEY (grid_result_id)
            REFERENCES grid_result (grid_result_id)
            ON DELETE CASCADE
    )
    """,
    "buses_result": """CREATE TABLE IF NOT EXISTS buses_result (
        version_id varchar(10) NOT NULL,
        grid_result_id integer,
        bus_id integer,
        name varchar,
        vn_kv double precision,
        type varchar,
        zone varchar,
        in_service boolean,
        geom geometry(Point,3035),

        CONSTRAINT fk_buses_result_version_id
            FOREIGN KEY (version_id)
            REFERENCES version (version_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_buses_result_grid_result_id
            FOREIGN KEY (grid_result_id)
            REFERENCES grid_result (grid_result_id)
            ON DELETE CASCADE
    )
    """,
    "loads_result": """CREATE TABLE IF NOT EXISTS loads_result (
        version_id varchar(10) NOT NULL,
        grid_result_id integer,
        load_id integer,
        bus integer,
        p_mw double precision,
        q_mvar double precision,
        geom geometry(Point,3035),

        CONSTRAINT fk_loads_result_version_id
            FOREIGN KEY (version_id)
            REFERENCES version (version_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_loads_result_grid_result_id
            FOREIGN KEY (grid_result_id)
            REFERENCES grid_result (grid_result_id)
            ON DELETE CASCADE
    )
    """,
    "transformers_result": """CREATE TABLE IF NOT EXISTS transformers_result (
        version_id varchar(10) NOT NULL,
        grid_result_id integer,
        trafo_id integer,
        from_bus integer,
        to_bus integer,
        std_type varchar,
        sn_mva double precision,
        vn_hv_kv double precision,
        vn_lv_kv double precision,
        vk_percent double precision,
        vkr_percent double precision,
        pfe_kw double precision,
        i0_percent double precision,
        geom geometry(Point,3035),

        CONSTRAINT fk_transformers_result_version_id
            FOREIGN KEY (version_id)
            REFERENCES version (version_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_transformers_result_grid_result_id
            FOREIGN KEY (grid_result_id)
            REFERENCES grid_result (grid_result_id)
            ON DELETE CASCADE
    )
    """,
    "ext_grids_result": """CREATE TABLE IF NOT EXISTS ext_grids_result (
        version_id varchar(10) NOT NULL,
        grid_result_id integer,
        ext_grid_id integer,
        bus integer,
        vm_pu double precision,
        va_degree double precision,
        geom geometry(Point,3035),

        CONSTRAINT fk_ext_grids_result_version_id
            FOREIGN KEY (version_id)
            REFERENCES version (version_id)
            ON DELETE CASCADE,
        CONSTRAINT fk_ext_grids_result_grid_result_id
            FOREIGN KEY (grid_result_id)
            REFERENCES grid_result (grid_result_id)
            ON DELETE CASCADE
    )
    """,
    "municipal_register": """CREATE TABLE IF NOT EXISTS municipal_register (
        plz integer,
        mun_id bigint,
        ags bigint,
        name varchar,
        gemeente_verband varchar,
        qkm double precision,
        regiostar7 integer,
        regiostar17 integer,
        geom geometry(Polygon,3035)
    )
    """,
    "transformer_classified": """CREATE TABLE IF NOT EXISTS transformer_classified (
        classification_id integer NOT NULL,
        muni_id bigint,
        plz integer,
        lcid integer,
        bcid integer,
        cluster_type integer,
        sn_mva double precision,
        geom geometry(Point,3035),

        CONSTRAINT fk_transformer_classified_classification_id
            FOREIGN KEY (classification_id)
            REFERENCES classification_version (classification_id)
            ON DELETE CASCADE
    )
    """,
    "sample_set": """CREATE TABLE IF NOT EXISTS sample_set (
        classification_id integer NOT NULL,
        plz integer,
        muni_id bigint,

        CONSTRAINT sample_set_pkey PRIMARY KEY (classification_id, plz),
        CONSTRAINT fk_sample_set_classification_id
            FOREIGN KEY (classification_id)
            REFERENCES classification_version (classification_id)
            ON DELETE CASCADE
    )
    """,
}

# Temporary tables used during processing
TEMP_CREATE_QUERIES = {
    "buildings_tem": """
        CREATE TABLE IF NOT EXISTS buildings_tem (
            osm_id bigint,
            plz integer,
            kcid integer,
            bcid integer,
            area double precision,
            type varchar,
            households_per_building double precision,
            peak_load_in_kw double precision,
            floors integer,
            vertice_id integer,
            connection_point geometry(Point,3035),
            center geometry(Point,3035),
            geom geometry(Polygon,3035)
        );
        """,
    "ways_tem": """
        CREATE TABLE IF NOT EXISTS ways_tem (
            gid SERIAL PRIMARY KEY,
            clazz integer,
            source integer,
            target integer,
            cost double precision,
            reverse_cost double precision,
            geom geometry(LineString,3035),
            way_id bigint,
            plz integer
        );
        """,
}

REFRESH_QUERIES = {
    "refresh_mv": """REFRESH MATERIALIZED VIEW municipal_register""",
}

